# Site settings
title: Jonathan Reeve 
email: jon.reeve@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
        The personal website of Jonathan Reeve. Digital humanities, hacks, ideas, improvements. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonreeve.com" # the base hostname & protocol for your site
twitter_username: j0_0n 
github_username: JonathanReeve 

# Build settings
markdown: redcarpet
