title: Jonathan Reeve
description: Computational Literary Analysis
url: http://jonreeve.com
author:
  name: Jonathan Reeve
  email: jon.reeve@gmail.com
  twitter: j0_0n
nav: 
  - name: cv
    url: /cv
  - name: tags
    url: /tags
