title: Jonathan Reeve
description: Computational Literary Analysis
url: http://jonreeve.com
author:
  name: Jonathan Reeve
  email: jon.reeve@gmail.com
  twitter: j0_0n
  github: JonathanReeve
nav: 
  - name: posts
    url: /#posts
  - name: CV
    url: /cv
  - name: tags
    url: /tags
  - name: feed
    url: /feed.xml
greeting: Hi. My name is Jonathan Reeve. I'm a PhD candidate in **computational literary analysis** at Columbia University. I write computer programs that help us understand novels and poetry.
coda: "I believe in openness. This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/). All content © Jonathan Reeve 2018. Hand-coded with love, using exclusively free and open-source software, including [Metalsmith](http://www.metalsmith.io/), [Pug](https://pugjs.org/), and [Sass](http://sass-lang.com/). Hosted on [GitHub](https://github.com) and served with [Netlify](https://netlify.com). Icons by Nhor, via [The Noun Project](https://thenounproject.com). [Buy me a coffee](https://www.buymeacoffee.com/vaIVQZH) or support me [via Libera Pay](https://liberapay.com/JonathanReeve/donate) or Bitcoin: 3Qvm1DwzFGk3L1Eb6yeg5Nbc6db8sZUnbK."
