title: Jonathan Reeve
description: Digital Humanities, Hacks, Improvements
url: http://jonreeve.com
author:
  name: Jonathan Reeve
  email: jon.reeve@gmail.com
  twitter: j0_0n
nav: 
  - name: cv
    url: cv
