name: "CI"
on:
  pull_request:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
      - name: Install Nix
        uses: cachix/install-nix-action@v13
      - name: Install Rib and Build
        uses: cachix/cachix-action@v10  # This also runs nix-build.
        with:
          name: srid
      - run: nix-build
      - run: nix-shell --run "echo OK"
      - name: Build Site
        run: nix-shell --run "cabal run"
      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dest # The folder the action should deploy.
