name: "Publish site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build sources 🔧
        run: |
          nix build
      - name: Generate HTML 🔧
        run: |
          mkdir ./output
          export TARGET=$(pwd)/output
          ./result/bin/jonreeve gen $TARGET
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
